services:
  redis:
    image: redis:7-alpine
    container_name: veze_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
  uniqverse:
    build:
      context: ./VEZEPyUniQVerse
    container_name: veze_uniqverse
    ports:
      - "${UNI_PORT:-8010}:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://127.0.0.1:8000/health\")' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
      game:
        condition: service_started
      email:
        condition: service_started
      xengine:
        condition: service_started

  game:
    build:
      context: ./VEZEPyGame
    container_name: veze_game
    ports:
      - "${GAME_PORT:-8012}:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen(\"http://127.0.0.1:8000/health\").getcode()==200 else 1)' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  email:
    build:
      context: ./VEZEPyEmail
    container_name: veze_email
    ports:
      - "${EMAIL_PORT:-8014}:8000"   # HTTP API/UI (changed to avoid conflicts)
      - "${EMAIL_SMTP_25:-2526}:25"     # SMTP (dev) - override EMAIL_SMTP_25 to change
      - "${EMAIL_SMTP_587:-2588}:587"   # SMTP Submission (dev) - override EMAIL_SMTP_587
      - "${EMAIL_SMTP_465:-2466}:465"   # SMTPS (dev) - override EMAIL_SMTP_465
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen(\"http://127.0.0.1:8000/health\").getcode()==200 else 1)' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  xengine:
    build:
      context: ./VEZEPyXEngine
    container_name: veze_xengine
    ports:
      - "${XENGINE_PORT:-8006}:8006"
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen(\"http://127.0.0.1:8006/health\").getcode()==200 else 1)' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - REDIS_URL=redis://redis:6379/3
      - X_DEFAULT_HANDLE=@shivaveld_idyll
      - POST_TO_X_ENABLED=false
      # Provide one of these to enable real X API calls (optional)
      # - X_BEARER_TOKEN=${X_BEARER_TOKEN}
      # - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
    depends_on:
      redis:
        condition: service_healthy

  xengine-worker:
    build:
      context: ./VEZEPyXEngine
    container_name: veze_xengine_worker
    command: ["python","-m","app.worker"]
    environment:
      - REDIS_URL=redis://redis:6379/3
    depends_on:
      redis:
        condition: service_healthy

networks:
  default:
    name: veze-net